name: Bootstrap Terraform Backend

on:
  workflow_dispatch:  # Manually triggered via GitHub UI

jobs:
  bootstrap:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-2
      BUCKET_NAME: my-terraform-backend-prod
      DYNAMO_TABLE: terraform-locks
      TF_STATE_KEY: prod/terraform.tfstate

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Create S3 bucket if not exists
        run: |
          aws s3api head-bucket --bucket $BUCKET_NAME || \
          aws s3api create-bucket \
            --bucket $BUCKET_NAME \
            --region $AWS_REGION \
            --create-bucket-configuration LocationConstraint=$AWS_REGION

      - name: Enable versioning
        run: |
          aws s3api put-bucket-versioning \
            --bucket $BUCKET_NAME \
            --versioning-configuration Status=Enabled

      - name: Create DynamoDB lock table if not exists
        run: |
          aws dynamodb describe-table --table-name $DYNAMO_TABLE || \
          aws dynamodb create-table \
            --table-name $DYNAMO_TABLE \
            --attribute-definitions AttributeName=LockID,AttributeType=S \
            --key-schema AttributeName=LockID,KeyType=HASH \
            --billing-mode PAY_PER_REQUEST

      - name: Terraform init with backend
        working-directory: ./bootstrap-backend
        run: |
          terraform init \
            -backend-config="bucket=$BUCKET_NAME" \
            -backend-config="key=$TF_STATE_KEY" \
            -backend-config="region=$AWS_REGION" \
            -backend-config="dynamodb_table=$DYNAMO_TABLE" \
            -input=false
